.github/workflows/autorelease.yml

Added GitHub token environment variable to release verification step
Added `GH_TOKEN` environment variable using the default GitHub token in the autorelease workflow's verification step

fix: this time, but with gusto

---

.github/workflows/autorelease.yml

Simplified the auto-release workflow by utilizing a reusable workflow from init4tech/actions.
Replaced the custom release verification and creation logic with a standardized reusable workflow. The new workflow maintains the same trigger conditions (pushing to main branch with changes to Cargo.toml) while reducing complexity.
1. Update the version in Cargo.toml
2. Push changes to the main branch
3. Verify that a new release is automatically created with the updated version

feat: use shared autorelease workflow

---

bin/builder.rs
src/config.rs
src/tasks/oauth.rs
tests/bundle_poller_test.rs
tests/tx_poller_test.rs

Implements a shareable `Authenticator` which periodically refreshes the token it holds through a spawnable task. The interval for refreshing the token is configurable.
We share this authenticator across all the builder tasks that need it, and spawn the refresh task along with all other handles.
Closes ENG-633

feat(`oauth`): caching, shareable authenticator

---

Cargo.toml
bin/builder.rs
src/config.rs
src/service.rs
src/tasks/block.rs
src/tasks/bundler.rs
src/tasks/mod.rs
src/tasks/oauth.rs
src/tasks/submit.rs
src/tasks/tx_poller.rs
tests/bundle_poller_test.rs
tests/tx_poller_test.rs

This PR adds a `BundleFetcher` that the block builder uses to fetch bundles from the tx cache. It works similarly to the tx poller:
- it requests all bundles from the cache
- it filters out the already seen ones, keeping only the unique bundles
- it then sends these to the block task, which ingests the bundles one by one.
- When ingesting the bundles, right now only the txs are ingested, without respecting the set configurations for bundles, nor including the permit2 signed orders. This means that only the basic bundle functionality is implemented. Further implementation probably requires simulation work.
- There's no specific rule to where the txs of the bundle land in the block. We are simply extending the block with the new transactions.
Closes ENG-630.
DO NOT MERGE until ENG-633 is …

Adds bundle support to block builder

---

bin/builder.rs
src/service.rs

remove all endpoints except health check

simplify builder server

---

src/tasks/oauth.rs

The `select!` block was returning early because the `spawn` fn of the `authenticator` task was a future being awaited, instead of just returning the join handle.

chore(authenticator): fix authenticator task being dropped

---

bin/builder.rs
src/config.rs
src/tasks/block.rs
src/tasks/oauth.rs
src/tasks/submit.rs
tests/bundle_poller_test.rs
tests/tx_poller_test.rs

ensures that transactions which have already confirmed on the rollup are not included in the block
---
does not include removal of the "seen_txns" cache in the TxPoller class. going to make a separate PR for that

feat: filter confirmed transactions from the block

---

src/tasks/block.rs
src/tasks/tx_poller.rs

Given #31 , it's now possible to remove the naive solution of the `seen_txns` cache, and only filter transactions by whether they've been included on the rollup or not.

fix: remove naive seen_txns cache

---

Cargo.toml
src/config.rs
src/tasks/oauth.rs
tests/bundle_poller_test.rs
tests/tx_poller_test.rs

The aud claim is no longer needed with the new identity provider so we will omit

Removing the aud claim

---

Cargo.toml
bin/submit_transaction.rs
src/config.rs

on a loop
- sends a transaction to the target chain
- waits for it to mine
- sleeps
while collecting metrics on mine time
---
env vars
```
RPC_URL=target chain RPC URL
CHAIN_ID=target chain ID
AWS_KMS_KEY_ID=any KMS key funded on the target chain 
RECIPIENT_ADDRESS=the address of the recipient of the Ether
SLEEP_TIME=60 (or whatever)
```

feat: integration test

---

bin/submit_transaction.rs

chore(tx-submitter): add tx hash when transaction is successfully sent

---

Cargo.toml
bin/submit_transaction.rs
src/config.rs
src/signer.rs
src/tasks/block.rs
src/tasks/bundler.rs
src/tasks/oauth.rs
src/tasks/submit.rs
tests/bundle_poller_test.rs
tests/tx_poller_test.rs

- bump alloy up
- remove alloy primitives and import primitives from alloy core instead
- fix errors from alloy updates
- remove signet-types and reference zenith-types instead

chore: bumps alloy and zenith versions

---

src/tasks/oauth.rs

- changes the oauth fetcher to use an async http client to play nice with tokio during tests

fix: use an async http client

---

bin/submit_transaction.rs

- Longer timeout will give us better vis into blocks reverting
- cleanup a metric namespace for consistency

fix: longer timeout better metrics

---

Cargo.toml
bin/builder.rs
src/config.rs
src/tasks/block.rs
src/tasks/oauth.rs
src/tasks/submit.rs
tests/bundle_poller_test.rs
tests/tx_poller_test.rs

This PR adds bundle ingestion from the tx-pool to the Signet Builder.
- `InProgressBlock` building process now checks the cache for bundles
- Ingests any new bundles that it finds into the in progress block
- Changes the block submission call to use the BuilderHelper contract
- Stubs out bundle simulation (see [ENG-640](https://linear.app/initiates/issue/ENG-640/add-simulation-engine-to-the-example-builder))
This PR requires an environment variable (the builder helper contract address) be added to the configuration, and thus must go in after the config is added to the environment in [the-infra PR #308](https://github.com/init4tech/the-infra/pull/308)
Closes [ENG-549](https://linear.app/initiates/issue/ENG-629/add-bundle-with-signed-orders-support-by-using-the-helper-contract-to) …

feat: adds bundles to in progress block creation

---

Cargo.toml
bin/builder.rs
bin/submit_transaction.rs
src/config.rs
src/lib.rs
src/signer.rs
src/tasks/block.rs
src/tasks/bundler.rs
src/tasks/metrics.rs
src/tasks/mod.rs
src/tasks/oauth.rs
src/tasks/submit.rs
src/tasks/tx_poller.rs

use `init4()` to set up metrics and tracing
bring crate in line with clippy and code standards policies in other repos

chore: use bin base

---

src/tasks/tx_poller.rs

cleans up the code, saves a bit of resources, addresses comments from #60

Fix: various updates to the tx poller

---

bin/builder.rs
bin/submit_transaction.rs
src/config.rs
src/tasks/submit.rs
src/test_utils.rs
tests/block_builder_test.rs

Updates the builder to use the FromEnv derive
@rswanson this changes the names of the slot calc variables to match them as used in other repos

refactor: update config to use derive

---

src/tasks/metrics.rs

fix: updates the metrics task to use a pending tx watcher instead of `get_receipt`. this will allow it to wait for the transaction to confirm

fix: metrics previously did not wait for confirmation

---

src/tasks/block.rs
src/tasks/metrics.rs

deletes the sim error type, which is a 1-variant enum.  we can add this back later if we want to differentiate

refactor: delete sim error

---

src/tasks/submit.rs

Cleans up the submit task by breaking up functions more and improving tracing and control flow

refactor: misc cleaning on the submit task

---

src/config.rs
src/tasks/bundler.rs
src/tasks/tx_poller.rs

refactor: cleaning up poller logic
refactor: clean up the other poller too

refactor: cleaning up poller logic

---

bin/builder.rs
src/config.rs
src/lib.rs
src/quincey.rs
src/tasks/submit.rs

Refactor: break quincey into its own module and encapsulate its behavior to simplify tx submission flow

refactor: break out quincey

---

src/tasks/submit.rs

This PR makes the submit task future `continue` instead of `break` when it is done finishing its retry loop.
It was incorrectly breaking out of its submit loop after finishing one `retrying_handle_inbound` call.
Fixes ENG-1077

fix: continue instead of break in the submit task loop

---

bin/builder.rs
src/tasks/block/cfg.rs
src/tasks/block/mod.rs
src/tasks/block/sim.rs
src/tasks/mod.rs
src/test_utils.rs
tests/block_builder_test.rs

This PR refactors the block task into a module to prepare for separating block env preparation from simulation logic.

refactor: adds block module

---

.github/workflows/rust-ci.yml
Cargo.toml
tests/block_builder_test.rs

This PR sets an input boolean to install Foundry in the Rust action and sets up the integration test feature so that block simulation tests pass.

chore: adds foundry to rust tests

---

Cargo.toml
bin/builder.rs
src/signer.rs
src/tasks/block/sim.rs
src/tasks/cache/bundle.rs
src/tasks/cache/mod.rs
src/tasks/cache/task.rs
src/tasks/cache/tx.rs
src/tasks/mod.rs
tests/bundle_poller_test.rs
tests/tx_poller_test.rs

Feat: adds a cache task to replace the ad-hoc cache tasks in `block.rs` this cache task relies on env information from the env builder

feat: cache task

---

Cargo.toml
bin/builder.rs
src/config.rs
src/tasks/block/cfg.rs
src/tasks/block/sim.rs
src/tasks/cache/bundle.rs
src/tasks/cache/mod.rs
src/tasks/cache/task.rs
src/tasks/env.rs
src/tasks/metrics.rs
src/test_utils.rs
tests/block_builder_test.rs
tests/bundle_poller_test.rs
tests/cache.rs
tests/env.rs
tests/tx_poller_test.rs

Integration for downstack PRs for cache and env tasks

refactor: integrate env and cache tasks

---

Cargo.toml
bin/submit_transaction.rs
src/config.rs
src/utils.rs

chore(deps): upgrade to latest alloy/sdk/trevm

---

Cargo.toml
bin/submit_transaction.rs
src/config.rs
src/tasks/block/sim.rs
src/tasks/submit.rs

This PR includes several fixes and refactors to the channel submission logic. 
- Handle 403 errors with `Skip`s instead of erroring
- Adds `retry_count` increments to some code paths that weren't previously ticking the count
- Adds per-slot limiting to the block building loop so that the retry function doesn't simply get called again after 3 attempts
- Explicitly logs the `call` results of the blob transaction to aid with debugging
- Adds gas bumping logic to the submit task to facilitate transaction replacement
Additionally, there are some configuration changes that needed to be made.
- Additional broadcast hosts was just pointing back at the host RPC, which was adding noise to the logs and interfering with nonce debugging. This PR makes it optional and un-sets the duplicate host-rpc …

fix: submit channel refactors

---

src/tasks/submit.rs

This PR adds the host fills from the build block to the rollup block header.
Closes ENG-1080

feat: add host fills from built block to block header

---

Cargo.toml
src/quincey.rs
src/tasks/submit.rs

- sets the `signet-sdk` dependency back to using latest by removing the previously-set rev hash.

chore: sets signet-sdk dependency back to latest

---

Cargo.toml

This PR bumps the `builder` crate version  to `0.2.0`.
Closes ENG-1038

chore: bump builder to 0.2.0

---

Cargo.lock
Cargo.toml
src/quincey.rs
src/tasks/cache/bundle.rs

Accomodates the new shared token changes.

chore(deps): bump bin-base

---

Cargo.lock
Cargo.toml
src/tasks/block/sim.rs
src/tasks/submit/task.rs
src/utils.rs

We were calculating the deadline by subtracting from an `Instant::now()`, which we shouldn't do. We now simply subtract the buffer from the remaining time in the slot and add the result to the current instant instead.
This also switches to using `chrono` for anything regarding timestamps instead of using `std`, for parity with the slot calculator. Everything else uses `Instant` or `Duration` already.
Closes ENG-1167
Closes ENG-1019

fix: properly calculate deadline, use `chrono` for calculating timestamps

---

README.md

These were out of date. Some were missing, and `RU_RPC_URL` is now `ROLLUP_RPC_URL`.

chore(README): update README env vars

---

Cargo.lock
Cargo.toml
bin/builder.rs
src/tasks/block/sim.rs
src/tasks/submit/task.rs

Contains the updates for native USD.

chore(deps): update SDK

---

src/tasks/env.rs

This is calculating a timestamp based on a block number, instead of a timestamp.

fix(env): fix next timestamp calculation

---

Cargo.lock
Cargo.toml
README.md
bin/submit_order.rs
src/lib.rs

Closes ENG-1193
Requires some cleanup as this is lifted from the orders roundtrip script

feat(bin): order submitter

---

src/config.rs
src/tasks/cache/bundle.rs
src/tasks/cache/tx.rs
src/tasks/submit/prep.rs
src/test_utils.rs

Use `url::Url` in the config where appropriate. This does not change over the additional broadcast urls, as `connect` accepts a `&str`

refactor: use Url in the config

---

src/tasks/env.rs

The stream sub produces headers, so we no longer need to get a header

refactor: remove bogus await from env task

---

README.md

chore(readme): fixes

---

README.md
src/config.rs
src/test_utils.rs

Adds an environment variable to the config for interacting with a `FLASHBOTS_ENDPOINT` API. This is to enable the Builder to submit blocks to the configured Flashbots destination.

config: adds flashbots endpoint env var

---

src/tasks/submit/builder_helper/submit.rs

Adds spans to a few spawned tasks in the builder helper submittter

feat: span the provider send spawns
